#index:
#    path: /
#    controller: App\Controller\DefaultController::index
user:
  type:     rest
  resource: App\Controller\UserController

news:
  type:     rest
  resource: App\Controller\NewsController