fos_user:
  resource: "@FOSUserBundle/Resources/config/routing/all.xml"

_wdt:
  resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
  prefix:   /_wdt

_profiler:
  resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
  prefix:   /_profiler

user:
  type:     rest
  prefix:   /api
  resource: App\Controller\UserController

news:
  type:     rest
  prefix:   /api
  resource: App\Controller\NewsController

app.swagger:
  path: /api/doc.json
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger }

app.swagger_ui:
  path: /api/doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
